### ISSUE TITLE
Value Objects are immutable

### ISSUE THREAD

**Issue by iberodev** [slashdotdash/cqrs-best-practices#1]
you mention `not to use value objects in domain events because value objects may change` but that's not correct.
Value objects never change. They're immutable.
A domain event has only value objects.
For example:

```
class SomethingHappened {
   Guid Id { get; }
   public SomethingHappened(Guid id){
       Id = id;
   }
}
```

The `Id` Guid is a value object yet the event is immutable and so it is the Id.

Where did you get that statement from?

Thanks

**Comment by slashdotdash** [comment]
You could change definition of the value object (the code) which might break existing stored values. 

As an example you could create a value object to model an address which has fields for street and county. 

```c#
class Address {
  string Street { get; }
  string County { get; }

  public Address(string street, string county) {
    Street = street;
    County = county;
  }
}

class CustomerMoved {
   Guid NewAddress { get; }

   public CustomerMoved(Address newAddress){
     NewAddress = newAddress;
   }
}
```

If you, or someone else, later changed the Address value object class to rename street to address line 1 and add a new address line 2 field it would break any addresses already persisted in your domain events. 

```c#
class Address {
  string Line1 { get; }
  string Line2 { get; }
  string County { get; }

  public Address(string line1, string line2, string county) {
    Line1 = line1;
    Line2 = line2;
    County = county;
  }
}
```

By changing the value object's class definition (not the immutable values) I've broken any existing events unless I implement a data migration or event upcasting strategy. Not using value objects in domain events would remove the risk that someone could change their definition and inadvertently break existing stored events. 

Instead, my advice is to define domain events only using system types for properties since developers should be aware that changing event definitions will affect any existing events (there's less chance of accidentally breaking things).

```c#
class CustomerMoved {
  string Street { get; }
  string County { get; }

   public CustomerMoved(string street, string county){
     Street = street;
     County = county;
   }
}
```

Since Guid is a system type it's unlikely to be changed so doesn't suffer from the issue of changing user-defined value objects. 

Does that answer your question?

**Comment by iberodev** [comment]
Yes, I get your point and I agree with your recommendation. Thanks

**Comment by iberodev** [comment]
Just curious then, I can see your events are immutable in a way that you can only set values through the constructor. And this, I like.

What if your event contains a lot of information? Would you then have a constructor with many many parameters, or would you encapsulate fields in some objects "breaking" your recommendation of trying to use only system types in your events?

Or would you then have some kind of value object such as the following `PersonalDetails`:

```
public class UserCreated
    : IDomainEvent
{
    private readonly PersonalDetails _personalDetails;

    public Guid AggregateId { get; }
    public DateTime CreatedOn { get; }
    public string Name => _personalDetails.Name;
    public string LastName => _personalDetails.LastName;
    public string Email => _personalDetails.Email;

    public UserCreated(
        Guid aggregateId, 
        DateTime createdOn,
        PersonalDetails personalDetails)
    {
        AggregateId = aggregateId;
        CreatedOn = createdOn;
        _personalDetails = personalDetails;
    }
}
```

that's a dilemma I always have and I tend to use the approach above.

That way if you decide to rename `Name` to `FirstName` inside `PersonalDetails` nothing at all would be broken for the event. From a read perspective, the event remains being "immutable" thanks to encapsulation. So it's a bit of a hybrid approach
